---Shared symbol rules; only actual language differences need overrides.
---@type SymbolAliasRule[]
return {
  { trigger = "<=", name = "le", latex = "\\le", opts = { wordTrig = false } },
  { trigger = ">=", name = "ge", latex = "\\ge", opts = { wordTrig = false } },
  { trigger = "!=", name = "ne", latex = "\\ne", opts = { wordTrig = false } },
  {
    trigger = "...",
    name = "horizontal dots",
    latex = "\\dots",
    typst = "dots.h",
    opts = { wordTrig = false },
  },
  {
    trigger = "+-",
    name = "plus minus",
    latex = "\\pm",
    typst = "plus.minus",
    opts = { wordTrig = false },
  },
  {
    trigger = "-+",
    name = "minus plus",
    latex = "\\mp",
    typst = "minus.plus",
    opts = { wordTrig = false },
  },
  { trigger = "=>", name = "implies", latex = "\\implies", typst = "=>", opts = { wordTrig = false } },
  { trigger = "==", name = "iff", latex = "\\iff", opts = { wordTrig = false } },
  {
    trigger = "->",
    name = "right arrow (to)",
    latex = "\\to",
    typst = "->",
    opts = { wordTrig = false },
  },
  {
    trigger = { "<-", "<>-" },
    name = "left arrow (get)",
    latex = "\\gets",
    typst = "<-",
    opts = { wordTrig = false },
  },
  {
    trigger = "-->",
    name = "uniform convergence",
    latex = "\\rightrightarrows",
    opts = { wordTrig = false, priority = 1200 },
  },
  { trigger = "|->", name = "mapsto", latex = "\\mapsto", typst = "mapsto", opts = { wordTrig = false } },
  { trigger = ":=", name = "definition", latex = "\\coloneqq", typst = "colon.eq", opts = { wordTrig = false } },
  { trigger = ">>", name = "much greater", latex = "\\gg", typst = "gt.double", opts = { wordTrig = false } },
  { trigger = "<<", name = "much less", latex = "\\ll", typst = "lt.double", opts = { wordTrig = false } },
  { trigger = "~>", name = "successor relation", latex = "\\succ", typst = "succ", opts = { wordTrig = false } },
  { trigger = "~<", name = "predecessor relation", latex = "\\prec", typst = "prec", opts = { wordTrig = false } },
  {
    trigger = ">~",
    name = "successor equal relation",
    latex = "\\succcurlyeq",
    typst = "succ.curly.eq",
    opts = { wordTrig = false },
  },
  {
    trigger = "<~",
    name = "predecessor equal relation",
    latex = "\\preccurlyeq",
    typst = "prec.curly.eq",
    opts = { wordTrig = false },
  },
  { trigger = "~~", name = "approx", latex = "\\approx", typst = "approx", opts = { wordTrig = false } },
  { trigger = "=~", name = "similar", latex = "\\sim", typst = "tilde.op", opts = { wordTrig = false } },
  { trigger = "~=", name = "congruent", latex = "\\cong", typst = "tilde.equiv", opts = { wordTrig = false } },
  { trigger = "=-", name = "equivalent", latex = "\\equiv", typst = "equiv", opts = { wordTrig = false } },
  { trigger = "|=", name = "models", latex = "\\models", typst = "models", opts = { wordTrig = false } },
  { trigger = "|-", name = "entails", latex = "\\vdash", opts = { wordTrig = false } },
  { trigger = "<|", name = "normal subgroup", latex = "\\trianglelefteq", opts = { wordTrig = false } },
  { trigger = ",.", name = "thin comma", latex = ",\\, ", opts = { wordTrig = false } },
  { trigger = "-.", name = "center dot", latex = "\\cdot", typst = "dot.c", opts = { wordTrig = false } },
  { trigger = "o-", name = "circ", latex = "\\circ", opts = { wordTrig = false } },
  { trigger = { "tim", "xx" }, name = "times", latex = "\\times", typst = "times" },
  { trigger = "div", name = "division", latex = "\\div", typst = "div" },
  { trigger = "mod", name = "mod", latex = "\\bmod" },
  { trigger = "TT", name = "true", latex = "\\mathbf{T}" },
  { trigger = "FF", name = "false", latex = "\\mathbf{F}" },
  { trigger = "bhb", name = "subset", latex = "\\subset" },
  { trigger = "bhp", name = "supset", latex = "\\supset" },
  { trigger = "oc", name = "proportional", latex = "\\propto", typst = "prop" },
  { trigger = "ooo", name = "infinity", latex = "\\infty" },
  { trigger = "nabla", name = "nabla", latex = "\\nabla", typst = "nabla" },
  { trigger = "ang", name = "angle", latex = "\\angle", typst = "angle" },
  { trigger = "tri", name = "triangle", latex = "\\triangle", typst = "triangle.stroked.t" },
  { trigger = "deg", name = "degree", latex = "\\degree", typst = "degree" },
  { trigger = "par", name = "parallel", latex = "\\parallel", typst = "parallel" },
  { trigger = "perp", name = "perpendicular", latex = "\\perp", typst = "perp" },
  { trigger = { "exist", "EE" }, name = "exists", latex = "\\exists", typst = "exists" },
  { trigger = { "forall", "AA" }, name = "forall", latex = "\\forall", typst = "forall" },
  { trigger = "empty", name = "empty set", latex = "\\emptyset", typst = "emptyset" },
  { trigger = "cap", name = "intersection", latex = "\\cap", typst = "inter" },
  { trigger = "cup", name = "union", latex = "\\cup", typst = "union" },
  { trigger = "yw", name = "because", latex = "\\because", typst = "because" },
  { trigger = "sy", name = "therefore", latex = "\\therefore", typst = "therefore" },
  { trigger = "and", name = "logical and", latex = "\\land" },
  { trigger = "or", name = "logical or", latex = "\\lor" },
  { trigger = "not", name = "logical not", latex = "\\lnot" },
}
